export const FormsGames = [
    {
      "checked": true,
      "description": "Juego para el cual desea realizar la recarga",
      "disabled": false,
      "label": "juego",
      "name": "name_1110064419",
      "placeholder": "Juego",
      "required": true,
      "rowIndex": 0,
      "type": "text",
      "value": "",
      "variant": "Input",
      "min": 2,
      "max": 20
    },
    {
      "checked": true,
      "description": "Cantidad de monedas a comprar",
      "disabled": false,
      "label": "Monedas",
      "name": "name_2435070634",
      "placeholder": "Cantidad",
      "required": true,
      "rowIndex": 0,
      "type": "number",
      "value": "",
      "variant": "Input",
      "min": 1
    },
    {
      "checked": true,
      "description": "Id de la cuenta a realizar la recarga",
      "disabled": false,
      "label": "ID de la cuenta",
      "name": "name_9680451077",
      "placeholder": "Id de la cuenta",
      "required": true,
      "rowIndex": 0,
      "type": "",
      "value": "",
      "variant": "Input",
      "min": 1
    },
    {
      "checked": true,
      "description": "Región o servidor al que pertenece la cuenta ",
      "disabled": false,
      "label": "Región o servidor",
      "name": "name_5232852522",
      "placeholder": "Región o servidor al que pertenece la cuenta ",
      "required": true,
      "rowIndex": 0,
      "type": "text",
      "value": "",
      "variant": "Input",
      "min": 0
    },
    {
      "checked": true,
      "description": "Acepto los terminos y condiciones correspondientes a la información",
      "disabled": false,
      "label": "Acepto que la información introducida en este formulario es la correcta correspondiente a como se solicita",
      "name": "name_1930221828",
      "placeholder": "Acepto que la información introducida en este formulario es la correcta correspondiente a como se solicita.",
      "required": true,
      "rowIndex": 0,
      "type": "",
      "value": "",
      "variant": "Checkbox"
    }
  ]