export const FormsGames = [
    {
      "checked": true,
      "description": "Juego para el cual desea realizar la recarga",
      "disabled": true,
      "label": "juego",
      "name": "name_1110064419",
      "placeholder": "Juego",
      "required": true,
      "rowIndex": 0,
      "type": "text",
      "value": "",
      "variant": "Input",
      "min": 2,
      "max": 20
    },
    {
      "checked": true,
      "description": "Cantidad de monedas a comprar",
      "disabled": false,
      "label": "Monedas",
      "name": "name_2435070634",
      "placeholder": "Cantidad",
      "required": true,
      "rowIndex": 0,
      "type": "text",
      "value": "",
      "variant": "Input",
      "min": 1
    },
    {
      "checked": true,
      "description": "Id de la cuenta a realizar la recarga",
      "disabled": false,
      "label": "ID de la cuenta",
      "name": "name_9680451077",
      "placeholder": "Id de la cuenta",
      "required": true,
      "rowIndex": 0,
      "type": "",
      "value": "",
      "variant": "Input",
      "min": 1
    },
        {
      "checked": true,
      "description": "Nombre del jugador al que pertenece la cuenta",
      "disabled": false,
      "label": "Nombre del jugador",
      "name": "name_7004455052",
      "placeholder": "Nombre del jugador",
      "required": true,
      "rowIndex": 0,
      "type": "",
      "value": "",
      "variant": "Input",
      "min": 1
    },
    {
      "checked": true,
      "description": "Region",
      "disabled": false,
      "label": "Región ",
      "name": "name_5232852522",
      "placeholder": "Region al que pertenece la cuenta ",
      "required": true,
      "rowIndex": 0,
      "type": "text",
      "value": "",
      "variant": "Input",
      "min": 0
    },
    {
      "checked": true,
      "description": "Servidor",
      "disabled": false,
      "label": "Servidor",
      "name": "name_4833852072",
      "placeholder": "Servidor al que pertenece la cuenta ",
      "required": true,
      "rowIndex": 0,
      "type": "text",
      "value": "",
      "variant": "Input",
      "min": 0
    },
    {
      "checked": true,
      "description": "",
      "disabled": false,
      "label": "Acepto los términos y condiciones.",
      "name": "name_1930221828",
      "placeholder": "",
      "required": true,
      "rowIndex": 0,
      "type": "",
      "value": "",
      "variant": "Checkbox"
    }    
  ]

  